theme = "sonokai"

[editor]
bufferline = "always"
text-width = 79
rulers = [80]
line-number = "relative"
auto-save = true

[editor.whitespace.render]
newline = "all"
nbsp = "all"
space = "none"
tab = "none"

[editor.statusline]
left = ["mode", "spacer", "version-control" ,"spinner", "read-only-indicator", "file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"

[keys.select]
j = "extend_char_left"
k = "extend_visual_line_down"
l = "extend_visual_line_up"
"ö" = "extend_char_right"
"ß" = "extend_to_line_end"
"0" = "extend_to_line_start"
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
Y = "yank_joined_to_clipboard"
R = "replace_selections_with_clipboard"

[keys.normal]
a = ["ensure_selections_forward", "collapse_selection", "move_char_right", "insert_mode"]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_visual_line_up"
K = "join_selections"
J = "keep_selections"
X = "extend_line_above"
"ö" = "move_char_right"
"ß" = "goto_line_end"
"0" = "goto_line_start"
"C-n" = "extend_search_next"
"C-p" = "extend_search_prev"
d = "delete_selection_noyank"
c = "change_selection_noyank"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
Y = "yank_joined_to_clipboard"
R = "replace_selections_with_clipboard"
"C-c" = ":write-quit"

[keys.normal.g]
j = "goto_line_start"
k = "move_line_down"
l = "move_line_up"
a = "code_action"
q = ":reflow"
"ö" = "goto_line_end"

[keys.normal.z]
k = "scroll_down"
l = "scroll_up"

[keys.normal.space]
c = "toggle_comments"

[keys.select.space]
c = "toggle_comments"
