#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

source $HOME/.config/sketchybar/colors.sh
source $HOME/.config/sketchybar/icons.sh

export FONT="JetBrainsMono Nerd Font"
export NERD_FONT="JetBrainsMono Nerd Font"

sketchybar --bar height=50               \
                 margin=10      \
                 y_offset=20             \
                 position=top            \
                 padding_left=20         \
                 padding_right=20        \
                 color=0xcc282c34        \
                 shadow=on               \
                 corner_radius=20

sketchybar --default updates=when_shown                       \
                     drawing=on                               \
                     icon.font="$NERD_FONT:Bold:24.0"      \
                     icon.color=0xffffffff                    \
                     label.font="$FONT:Bold:18.0"            \
                     label.color=0xffffffff                   \
                     label.padding_left=4                     \
                     label.padding_right=4                    \
                     icon.padding_left=4                      \
                     icon.padding_right=4


source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/window_title.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/vpn.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/darkside.sh

sketchybar --update

echo "sketchybar configuration loaded.."

